# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    kernel.listener.CacheListener:
        class: ISETSO\UserBundle\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    user.voter:
        class: ISETSO\UserBundle\EventListener\UserVoter
        arguments: ['@security.access.decision_manager']
        tags:
            - { name: security.voter }
    user.onligne_user_listener:
        class: ISETSO\UserBundle\EventListener\OnligneUserListener
        arguments: [@security.context, @fos_user.user_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }